apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: task-service-replicaset
  labels:
    app: task-service
   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: todo-spring-task-service:latest
          imagePullPolicy: Never
