apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-service-replicaset
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: todo-laravel-user-service:latest
          imagePullPolicy: Never